apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "karakuri.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karakuri.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Files.Get "karakuri.yaml" | indent 4 }}
