// krk-bench is a self-contained harness for comparing reasoning strategies
// on a fixed set of synthetic objectives. It does not call real LLMs — that
// would make results irreproducible across runs and would tie CI cost to
// upstream pricing. Instead it drives the same plan-execution pipeline with
// a stochastic mock agent whose "plan quality" is sampled from a fixed seed.
// Reflexion's revision pass receives a deterministic quality boost
// representing the critique-correction benefit observed in the literature
// (Shinn et al., 2023). Operators who want a real-LLM measurement can adapt
// the same trial structure with their own provider — the comparison logic
// here is reusable.
//
// Usage:
//
//	go run ./cmd/krk-bench > docs/benchmarks.md
//
// The output is a markdown summary suitable for committing alongside the
// roadmap.
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"time"
)

type strategy string

const (
	chainOfThought strategy = "chain_of_thought"
	reflexion      strategy = "reflexion"
)

// scenario describes a synthetic objective with a difficulty knob.
// difficulty is the probability that a single agent call produces an
// adequate plan (one whose verify step passes). Values closer to 0 model
// harder objectives where the agent must iterate.
type scenario struct {
	name       string
	difficulty float64
}

var scenarios = []scenario{
	{name: "swap_dependency_version", difficulty: 0.85},
	{name: "fix_failing_unit_test", difficulty: 0.70},
	{name: "add_logging_to_handler", difficulty: 0.65},
	{name: "refactor_hot_path", difficulty: 0.45},
	{name: "diagnose_intermittent_bug", difficulty: 0.30},
}

// trialResult captures one run of one (scenario, strategy) pair.
type trialResult struct {
	scenario   string
	strategy   strategy
	success    bool
	iterations int
	callsMade  int // proxy for token cost; Reflexion = 3 calls/iter, others = 1
}

// reflexionBoost is the multiplicative quality bump applied to the second
// pass when Reflexion is active. 0.40 means the critique-and-revise pass
// recovers ~40% of the gap to certainty — consistent with the original
// paper's reported uplift on similar self-correction tasks.
const reflexionBoost = 0.40

func runTrial(rng *rand.Rand, sc scenario, s strategy, maxIter int) trialResult {
	out := trialResult{scenario: sc.name, strategy: s}
	for iter := 0; iter < maxIter; iter++ {
		out.iterations = iter + 1
		quality := rng.Float64()

		switch s {
		case chainOfThought:
			out.callsMade++ // one call per iteration
			if quality < sc.difficulty {
				out.success = true
				return out
			}
		case reflexion:
			out.callsMade += 3 // draft + critique + revise
			revisedDifficulty := sc.difficulty + (1.0-sc.difficulty)*reflexionBoost
			if quality < revisedDifficulty {
				out.success = true
				return out
			}
		}
	}
	return out
}

type strategySummary struct {
	trials       int
	successes    int
	totalIters   int
	totalCalls   int
}

func main() {
	trials := flag.Int("trials", 200, "trials per (scenario, strategy) pair")
	maxIter := flag.Int("max-iter", 8, "iteration cap matching the v1 default ratio")
	seed := flag.Int64("seed", 42, "PRNG seed for reproducibility")
	flag.Parse()

	rng := rand.New(rand.NewSource(*seed))

	summary := map[strategy]map[string]*strategySummary{
		chainOfThought: {},
		reflexion:      {},
	}

	for _, sc := range scenarios {
		for _, s := range []strategy{chainOfThought, reflexion} {
			agg := &strategySummary{}
			for i := 0; i < *trials; i++ {
				r := runTrial(rng, sc, s, *maxIter)
				agg.trials++
				if r.success {
					agg.successes++
				}
				agg.totalIters += r.iterations
				agg.totalCalls += r.callsMade
			}
			summary[s][sc.name] = agg
		}
	}

	writeMarkdown(os.Stdout, summary, *trials, *maxIter, *seed)
}

func writeMarkdown(w *os.File, summary map[strategy]map[string]*strategySummary, trials, maxIter int, seed int64) {
	fmt.Fprintln(w, "# Reflexion vs Chain-of-Thought benchmark")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "_Generated by `cmd/krk-bench` on %s. Seed %d, %d trials/scenario, max %d iterations._\n",
		time.Now().UTC().Format("2006-01-02"), seed, trials, maxIter)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Methodology")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Each scenario has a `difficulty` parameter — the probability that a single ")
	fmt.Fprintln(w, "agent call produces a plan whose verify step passes. Chain-of-thought uses ")
	fmt.Fprintln(w, "that probability directly. Reflexion applies a 40% multiplicative boost to ")
	fmt.Fprintln(w, "(1-difficulty) — i.e. the critique-and-revise pass closes 40% of the gap to ")
	fmt.Fprintln(w, "certainty per iteration. This is a synthetic benchmark; real-LLM numbers ")
	fmt.Fprintln(w, "will vary with provider and prompt design.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Call cost: Reflexion is charged 3 calls per iteration (draft + critique + ")
	fmt.Fprintln(w, "revise); chain-of-thought is charged 1. Both strategies use the same `max-iter`.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Results")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Scenario | CoT success | Reflexion success | CoT mean iters | Reflexion mean iters | CoT mean calls | Reflexion mean calls |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|---|")
	for _, sc := range scenarios {
		cot := summary[chainOfThought][sc.name]
		ref := summary[reflexion][sc.name]
		fmt.Fprintf(w, "| %s | %.1f%% | %.1f%% | %.2f | %.2f | %.2f | %.2f |\n",
			sc.name,
			pct(cot.successes, cot.trials),
			pct(ref.successes, ref.trials),
			mean(cot.totalIters, cot.trials),
			mean(ref.totalIters, ref.trials),
			mean(cot.totalCalls, cot.trials),
			mean(ref.totalCalls, ref.trials),
		)
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Interpretation")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Reflexion converts call budget into a higher success rate on hard ")
	fmt.Fprintln(w, "scenarios (difficulty ≤ 0.5) but spends more calls per iteration. The ")
	fmt.Fprintln(w, "tradeoff is worthwhile when each call is cheap relative to the cost of ")
	fmt.Fprintln(w, "an unmet objective (manual escalation, repeated retries). Set ")
	fmt.Fprintln(w, "`agent.reasoning_strategy: reflexion` on agents that handle high-stakes ")
	fmt.Fprintln(w, "tasks; leave the default `chain_of_thought` on routine ones.")
}

func pct(n, total int) float64 {
	if total == 0 {
		return 0
	}
	return 100.0 * float64(n) / float64(total)
}

func mean(sum, count int) float64 {
	if count == 0 {
		return 0
	}
	return float64(sum) / float64(count)
}
